server:
  port: 9002


spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848  #配置的Nacos地址（本机的写localhost:8848，服务器的写IP地址）
        server-addr: 192.168.1.4:1111  #nginx的地址


management:
  endpoints:
    web:
      exposure:
        include: '*'